cookie:
  expiry_days: 30
  key: remember_me
  name: remember_me_cookie
credentials:
  usernames:
    sesa000000:
      email: sesa000000@se.com
      logged_in: false
      name: Just A User
      password: $2b$12$HM/MNfnaPhonsgrJfdqQguRAhHhMkMoMms6cnYocYqWZzxRLAw.wa
    sesa123456:
      email: sesa123456@se.com
      logged_in: false
      name: Sample User
      password: $2b$12$rw9UE.i3NcWle/djF3M0v.QL3nvMI0Gewjt3ovm11bKxgifvujf5S
    sesa654321:
      email: sesa654321@se.com
      logged_in: false
      name: Test User
      password: $2b$12$bSnGMwMqVi8n11qrLzybuOO/Z1oeYSPIWXLqMCUSfoH8wsg8orUQm
    sesa663731:
      email: sesa663731@se.com
      logged_in: false
      name: Emma Zambolin
      password: $2b$12$YZ83nojXzBQgmsP2ioZyz.hrLfMgBzUX0WqGR2pt3l2qpB4qITTeW
    sesa779046:
      email: sesa779046@se.com
      failed_login_attempts: 0
      logged_in: false
      name: Amal Dokkar
      password: $2b$12$iJwtHatQ4AuS.JqhAVwU3eYxuMRwP0WLl9nCQJDta3I2.O.dj7POS
